[env:waveshare_esp32_s3_touch_lcd_1_85]
platform = espressif32@^7.0.1
board = waveshare_esp32_s3_touch_lcd_1_85
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=1
  -DESP32QSPI_MAX_PIXELS_AT_ONCE=2048
  -DLV_CONF_INCLUDE_SIMPLE
  -Iinclude

lib_deps =
  moononournation/GFX Library for Arduino@1.6.0
  bblanchon/ArduinoJson@^7.4.2
  h2zero/NimBLE-Arduino@^2.5.0
  lvgl/lvgl@8.4.0

; After the first USB flash, change upload_port to the displayed IP
; or mDNS host and run PlatformIO upload with this environment.
[env:waveshare_esp32_s3_touch_lcd_1_85_ota]
extends = env:waveshare_esp32_s3_touch_lcd_1_85
upload_protocol = espota
upload_port = r48display.local
upload_flags =
  --auth=r48display

